[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "murky=lib/murky",
]
fs_permissions = [
  { access = "read-write", path = "script/target/" },
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
